# Dockerfile.tailscale
FROM ubuntu:24.04

# تثبيت الأدوات المطلوبة و Tailscale
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release iproute2 iptables sudo python3 python3-pip && \
    curl -fsSL https://tailscale.com/install.sh | sh

# تثبيت smtplib dependencies (Python)
RUN pip3 install --no-cache-dir email-validator

CMD ["sleep", "infinity"]
