name: ClusterRDP Smart (Test Edition)

on:
  workflow_dispatch:

jobs:
  cluster-rdp-smart:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Ensure script permissions
      run: chmod +x scripts/*.sh

    - name: List scripts for debugging
      run: ls -l scripts/

    - name: Launch Smart Cluster
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      run: |
        echo "⏱ Starting VM creation sequence..."
        # إنشاء أول VM مباشرة
        ./scripts/create_rdp_vm_smart.sh &
        # إنشاء الثاني بعد 15 دقيقة
        sleep 900 && ./scripts/create_rdp_vm_smart.sh &
        # إنشاء الثالث بعد 30 دقيقة إضافية
        sleep 1800 && ./scripts/create_rdp_vm_smart.sh &
        echo "✅ All VMs launched in smart sequence."

    - name: Monitor Cluster
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      run: ./scripts/monitor_cluster_smart.sh
